# Generated by Django 5.2.5 on 2025-08-27 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the volunteer form', max_length=200)),
                ('description', models.TextField(help_text='Description of the volunteer opportunity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this form is currently accepting signups')),
                ('unique_url', models.CharField(blank=True, help_text='Unique URL identifier for this form', max_length=50, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this volunteer slot', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this slot involves')),
                ('date', models.DateField(help_text='Date when this volunteer slot occurs')),
                ('start_time', models.TimeField(help_text='Start time of the volunteer slot')),
                ('end_time', models.TimeField(help_text='End time of the volunteer slot')),
                ('max_volunteers', models.PositiveIntegerField(default=1, help_text='Maximum number of volunteers for this slot')),
                ('current_signups', models.PositiveIntegerField(default=0, help_text='Current number of signups')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='signups.volunteerform')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the volunteer', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the volunteer', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes from the volunteer')),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='signups.volunteerslot')),
            ],
            options={
                'ordering': ['signed_up_at'],
            },
        ),
    ]
