# Generated by Django 5.2.5 on 2025-08-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerslot',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='volunteerslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='volunteerslot',
            name='start_time',
        ),
    ]
