# Generated by Django 5.2.5 on 2025-08-27 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_alter_volunteerslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the volunteer task type', max_length=200)),
                ('description', models.TextField(help_text='Standard description for this type of volunteer task')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this volunteer type is available for use')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='volunteerslot',
            name='volunteer_type',
            field=models.ForeignKey(blank=True, help_text='Type of volunteer task (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='signups.volunteertype'),
        ),
    ]
