# Generated by Django 5.2.5 on 2025-08-30 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_volunteertype_volunteerslot_volunteer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text="Family's last name", max_length=100)),
                ('email', models.EmailField(help_text='Primary email address for the family', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this family is active and can sign up')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['last_name'],
            },
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Predefined family (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='signups.family'),
        ),
    ]
