# Generated by Django 5.2.5 on 2025-08-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0004_family_volunteersignup_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteersignup',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
