# Generated by Django 5.2.5 on 2025-09-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0005_remove_family_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertype',
            name='credit_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Number of credit hours this activity is worth (e.g., 1.0 for lawn mowing, 0.5 for towel washing)', max_digits=4),
        ),
    ]
